vlstorage:
  persistentVolume:
    accessModes:
      - ReadWriteMany
    storageClassName: "nfs-g9-enp5s0-rwx"
vlinsert:
  service:
    annotations: 
      metallb.universe.tf/address-pool: vlinsert
    type: LoadBalancer
