apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault
  namespace: vault
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vault.aimhighergg.com`)
      kind: Rule
      middlewares:
        - name: vault-ip-whitelist
          namespace: vault
        #- name: vault-basic-auth
        #  namespace: vault
      services:
        - name: vault-ui-https
          kind: TraefikService
  tls:
    secretName: vault-aimhighergg-com-tls
