apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: ingress-traefik
type: Opaque
stringData:
  users: <path:secret/data/basic_auth#ingress>
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: monitoring
type: Opaque
stringData:
  users: <path:secret/data/basic_auth#ingress>
