apiVersion: v1
kind: Secret
metadata:
  name: ingress-basic-auth
  namespace: ingress-traefik
type: Opaque
stringData:
  users: <path:secret/data/basic_auth#ingress>
---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-basic-auth
  namespace: monitoring
type: Opaque
stringData:
  users: <path:secret/data/basic_auth#ingress>
---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-basic-auth
  namespace: argo-rollouts
type: Opaque
stringData:
  users: <path:secret/data/basic_auth#ingress>
---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-basic-auth
  namespace: longhorn-system
type: Opaque
stringData:
  users: <path:secret/data/basic_auth#ingress>
---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-basic-auth
  namespace: vault
type: Opaque
stringData:
  users: <path:secret/data/basic_auth#ingress>
