apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: vault-transport
  namespace: vault
spec:
  serverName: vault.vault.svc.cluster.local
  rootCAsSecrets:
    - vault-trust-bundle-secret
