apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: vault-ui-https
  namespace: vault
spec:
  weighted:
    services:
      - name: vault-ui
        port: 8200
        scheme: https
        serversTransport: vault-transport
