resources:
  - ./client-traffic-policy/client-traffic-policy.yaml
  - ./cluster-issuer/cluster-issuer.yaml
  - ./envoy-proxy/envoy-proxy.yaml
  - ./gateway/envoy/gateway.yaml
#  - ./gateway/nginx/gateway.yaml
  - ./gateway-class/gateway-class.yaml
  - ./http-route/http-route.yaml
  - ./security-policy/security-policy.yaml