resources:
  - bundle.yaml
  - rback.yaml

helmCharts:
  - name: trust-manager
    repo: https://charts.jetstack.io
    version: "0.18.0"
    releaseName: trust-manager
    namespace: cert-manager
    valuesFile: values.yaml
