apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <path:secret/data/ingress/app_1#name>
  namespace: <path:secret/data/ingress/app_1#namespace>
  annotations:
    ingressClassName: traefik
    cert-manager.io/cluster-issuer: ingress-traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - <path:secret/data/ingress/app_1#hosts>
      secretName: <path:secret/data/ingress/app_1#hosts>-tls
  rules:
    - host: <path:secret/data/ingress/app_1#hosts>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: <path:secret/data/ingress/app_1#service_name>
                port:
                  number: "<path:secret/data/ingress/app_1#service_port>"
