apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-rollouts-aimhighergg-com
  namespace: argo-rollouts
  annotations:
    ingressClassName: traefik
    cert-manager.io/cluster-issuer: ingress-traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: argo-rollouts-ip-whitelist@kubernetescrd,argo-rollouts-basic-auth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - argo-rollouts.aimhighergg.com
      secretName: argo-rollouts-aimhighergg-com-tls
  rules:
    - host: argo-rollouts.aimhighergg.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argo-rollouts-dashboard
                port:
                  number: 3100
