apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-aimhighergg-com
  namespace: longhorn-system
  annotations:
    ingressClassName: traefik
    cert-manager.io/cluster-issuer: ingress-traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: longhorn-system-ip-whitelist@kubernetescrd,longhorn-system-basic-auth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - longhorn.aimhighergg.com
      secretName: longhorn-aimhighergg-com-tls
  rules:
    - host: longhorn.aimhighergg.com
      http:
        paths:
          - backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
            path: /
            pathType: Prefix
