apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-aimhighergg-com
  namespace: monitoring
  annotations:
    ingressClassName: traefik
    cert-manager.io/cluster-issuer: ingress-traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    #traefik.ingress.kubernetes.io/router.middlewares: monitoring-ip-whitelist@kubernetescrd,monitoring-basic-auth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - prometheus.aimhighergg.com
      secretName: prometheus-aimhighergg-com-tls
  rules:
    - host: prometheus.aimhighergg.com
      http:
        paths:
          - backend:
              service:
                name: monitoring-backend-prometheus-db01-001
                port:
                  number: 9090
            path: /
            pathType: Prefix
