apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-aimhighergg-com
  namespace: vault
  annotations:
    ingressClassName: traefik
    cert-manager.io/cluster-issuer: ingress-traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: vault-ip-whitelist@kubernetescrd,vault-basic-auth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - vault.aimhighergg.com
      secretName: vault-aimhighergg-com-tls
  rules:
    - host: vault.aimhighergg.com
      http:
        paths:
          - backend:
              service:
                name: vault-ui
                port:
                  number: 8200
            path: /
            pathType: Prefix
