apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ingress-traefik
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: aim4highergg@gmail.com
    privateKeySecretRef:
      name: ingress-acme-account-key
    solvers:
    - http01:
        ingressClassName: traefik
