helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: "4.14.1"
    releaseName: ingress-nginx
    namespace: ingress-nginx
    additionalValuesFiles:
      - additional-values.yaml
    valuesFile: ../values.yaml
